/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGuestPostRouteImport } from './routes/_app/guest-post'
import { Route as AppGeneticsRouteImport } from './routes/_app/genetics'
import { Route as AppEvolutionRouteImport } from './routes/_app/evolution'
import { Route as AppCritiqueRouteImport } from './routes/_app/critique'
import { Route as AppCriticRouteImport } from './routes/_app/critic'
import { Route as AppCreationRouteImport } from './routes/_app/creation'
import { Route as AppAuthRouteImport } from './routes/_app/auth'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppPostIdRouteImport } from './routes/_app/post.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestPostRoute = AppGuestPostRouteImport.update({
  id: '/guest-post',
  path: '/guest-post',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneticsRoute = AppGeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRoute,
} as any)
const AppCritiqueRoute = AppCritiqueRouteImport.update({
  id: '/critique',
  path: '/critique',
  getParentRoute: () => AppRoute,
} as any)
const AppCriticRoute = AppCriticRouteImport.update({
  id: '/critic',
  path: '/critic',
  getParentRoute: () => AppRoute,
} as any)
const AppCreationRoute = AppCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/auth': typeof AppAuthRoute
  '/creation': typeof AppCreationRoute
  '/critic': typeof AppCriticRoute
  '/critique': typeof AppCritiqueRoute
  '/evolution': typeof AppEvolutionRoute
  '/genetics': typeof AppGeneticsRoute
  '/guest-post': typeof AppGuestPostRoute
  '/post/$id': typeof AppPostIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/auth': typeof AppAuthRoute
  '/creation': typeof AppCreationRoute
  '/critic': typeof AppCriticRoute
  '/critique': typeof AppCritiqueRoute
  '/evolution': typeof AppEvolutionRoute
  '/genetics': typeof AppGeneticsRoute
  '/guest-post': typeof AppGuestPostRoute
  '/': typeof AppIndexRoute
  '/post/$id': typeof AppPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/auth': typeof AppAuthRoute
  '/_app/creation': typeof AppCreationRoute
  '/_app/critic': typeof AppCriticRoute
  '/_app/critique': typeof AppCritiqueRoute
  '/_app/evolution': typeof AppEvolutionRoute
  '/_app/genetics': typeof AppGeneticsRoute
  '/_app/guest-post': typeof AppGuestPostRoute
  '/_app/': typeof AppIndexRoute
  '/_app/post/$id': typeof AppPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/creation'
    | '/critic'
    | '/critique'
    | '/evolution'
    | '/genetics'
    | '/guest-post'
    | '/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/creation'
    | '/critic'
    | '/critique'
    | '/evolution'
    | '/genetics'
    | '/guest-post'
    | '/'
    | '/post/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/auth'
    | '/_app/creation'
    | '/_app/critic'
    | '/_app/critique'
    | '/_app/evolution'
    | '/_app/genetics'
    | '/_app/guest-post'
    | '/_app/'
    | '/_app/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guest-post': {
      id: '/_app/guest-post'
      path: '/guest-post'
      fullPath: '/guest-post'
      preLoaderRoute: typeof AppGuestPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genetics': {
      id: '/_app/genetics'
      path: '/genetics'
      fullPath: '/genetics'
      preLoaderRoute: typeof AppGeneticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evolution': {
      id: '/_app/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/critique': {
      id: '/_app/critique'
      path: '/critique'
      fullPath: '/critique'
      preLoaderRoute: typeof AppCritiqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/critic': {
      id: '/_app/critic'
      path: '/critic'
      fullPath: '/critic'
      preLoaderRoute: typeof AppCriticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creation': {
      id: '/_app/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AppCreationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth': {
      id: '/_app/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post/$id': {
      id: '/_app/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuthRoute: typeof AppAuthRoute
  AppCreationRoute: typeof AppCreationRoute
  AppCriticRoute: typeof AppCriticRoute
  AppCritiqueRoute: typeof AppCritiqueRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppGeneticsRoute: typeof AppGeneticsRoute
  AppGuestPostRoute: typeof AppGuestPostRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPostIdRoute: typeof AppPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuthRoute: AppAuthRoute,
  AppCreationRoute: AppCreationRoute,
  AppCriticRoute: AppCriticRoute,
  AppCritiqueRoute: AppCritiqueRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppGeneticsRoute: AppGeneticsRoute,
  AppGuestPostRoute: AppGuestPostRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostIdRoute: AppPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
