/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGuestPostRouteImport } from './routes/_app/guest-post'
import { Route as AppGeneticsRouteImport } from './routes/_app/genetics'
import { Route as AppEvolutionRouteImport } from './routes/_app/evolution'
import { Route as AppCritiqueRouteImport } from './routes/_app/critique'
import { Route as AppCriticRouteImport } from './routes/_app/critic'
import { Route as AppCreationRouteImport } from './routes/_app/creation'
import { Route as AppAuthRouteImport } from './routes/_app/auth'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppPostIdRouteImport } from './routes/_app/post.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestPostRoute = AppGuestPostRouteImport.update({
  id: '/guest-post',
  path: '/guest-post',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneticsRoute = AppGeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRoute,
} as any)
const AppCritiqueRoute = AppCritiqueRouteImport.update({
  id: '/critique',
  path: '/critique',
  getParentRoute: () => AppRoute,
} as any)
const AppCriticRoute = AppCriticRouteImport.update({
  id: '/critic',
  path: '/critic',
  getParentRoute: () => AppRoute,
} as any)
const AppCreationRoute = AppCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AppAdminRoute
  '/auth': typeof AppAuthRoute
  '/creation': typeof AppCreationRoute
  '/critic': typeof AppCriticRoute
  '/critique': typeof AppCritiqueRoute
  '/evolution': typeof AppEvolutionRoute
  '/genetics': typeof AppGeneticsRoute
  '/guest-post': typeof AppGuestPostRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/post/$id': typeof AppPostIdRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AppAdminRoute
  '/auth': typeof AppAuthRoute
  '/creation': typeof AppCreationRoute
  '/critic': typeof AppCriticRoute
  '/critique': typeof AppCritiqueRoute
  '/evolution': typeof AppEvolutionRoute
  '/genetics': typeof AppGeneticsRoute
  '/guest-post': typeof AppGuestPostRoute
  '/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/post/$id': typeof AppPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/auth': typeof AppAuthRoute
  '/_app/creation': typeof AppCreationRoute
  '/_app/critic': typeof AppCriticRoute
  '/_app/critique': typeof AppCritiqueRoute
  '/_app/evolution': typeof AppEvolutionRoute
  '/_app/genetics': typeof AppGeneticsRoute
  '/_app/guest-post': typeof AppGuestPostRoute
  '/_app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/post/$id': typeof AppPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/auth'
    | '/creation'
    | '/critic'
    | '/critique'
    | '/evolution'
    | '/genetics'
    | '/guest-post'
    | '/.lovable/oauth/consent'
    | '/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/auth'
    | '/creation'
    | '/critic'
    | '/critique'
    | '/evolution'
    | '/genetics'
    | '/guest-post'
    | '/'
    | '/.lovable/oauth/consent'
    | '/post/$id'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_app/admin'
    | '/_app/auth'
    | '/_app/creation'
    | '/_app/critic'
    | '/_app/critique'
    | '/_app/evolution'
    | '/_app/genetics'
    | '/_app/guest-post'
    | '/_app/'
    | '/.lovable/oauth/consent'
    | '/_app/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guest-post': {
      id: '/_app/guest-post'
      path: '/guest-post'
      fullPath: '/guest-post'
      preLoaderRoute: typeof AppGuestPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genetics': {
      id: '/_app/genetics'
      path: '/genetics'
      fullPath: '/genetics'
      preLoaderRoute: typeof AppGeneticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evolution': {
      id: '/_app/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/critique': {
      id: '/_app/critique'
      path: '/critique'
      fullPath: '/critique'
      preLoaderRoute: typeof AppCritiqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/critic': {
      id: '/_app/critic'
      path: '/critic'
      fullPath: '/critic'
      preLoaderRoute: typeof AppCriticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creation': {
      id: '/_app/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AppCreationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth': {
      id: '/_app/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/post/$id': {
      id: '/_app/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuthRoute: typeof AppAuthRoute
  AppCreationRoute: typeof AppCreationRoute
  AppCriticRoute: typeof AppCriticRoute
  AppCritiqueRoute: typeof AppCritiqueRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppGeneticsRoute: typeof AppGeneticsRoute
  AppGuestPostRoute: typeof AppGuestPostRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPostIdRoute: typeof AppPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuthRoute: AppAuthRoute,
  AppCreationRoute: AppCreationRoute,
  AppCriticRoute: AppCriticRoute,
  AppCritiqueRoute: AppCritiqueRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppGeneticsRoute: AppGeneticsRoute,
  AppGuestPostRoute: AppGuestPostRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostIdRoute: AppPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
